
  CREATE TABLE "GDZC_CZ"."GDZC_BASE_EQUIPMENT_DISTRIBUTE" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"INPUT_VOLTAGE" NUMBER, 
	"INPUT_CURRENT" NUMBER, 
	"PRODUCT_CERTIFICATION" VARCHAR2(20 BYTE), 
	"PROTECTION_LEVEL" VARCHAR2(20 BYTE), 
	"CABINET_COLOR" VARCHAR2(20 BYTE), 
	"POWER_SOURCE" VARCHAR2(20 BYTE), 
	"LIGHTING_PROTECTION_LEVEL" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_BASE_EQUIPMENT_DISTR_PK" PRIMARY KEY ("EQUIPMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_DISTRIBUTE"."INPUT_VOLTAGE" IS '输入电压(单位V）';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_DISTRIBUTE"."INPUT_CURRENT" IS '输入电流值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_DISTRIBUTE"."PRODUCT_CERTIFICATION" IS '产品认证';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_DISTRIBUTE"."PROTECTION_LEVEL" IS '壳体防护等级';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_DISTRIBUTE"."CABINET_COLOR" IS '柜体颜色';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_DISTRIBUTE"."POWER_SOURCE" IS '供电来源';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_DISTRIBUTE"."LIGHTING_PROTECTION_LEVEL" IS '防雷等级';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_BASE_EQUIPMENT_DISTRIBUTE"  IS '配电设备';

  CREATE TABLE "GDZC_CZ"."GDZC_BASE_EQUIPMENT_E_MONITOR" 
   (	"COLUMN1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

  CREATE TABLE "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FIRE_FIGHT" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IMPLEMENTING_STANDARD" VARCHAR2(20 BYTE), 
	"HYDRA_EXPERIMENTAL_PRESSURE" VARCHAR2(20 BYTE), 
	"MAX_WORK_PRESSURE" VARCHAR2(20 BYTE), 
	"CONTROL_VALVE" VARCHAR2(20 BYTE), 
	"CABINET_COLOR" VARCHAR2(20 BYTE), 
	"SOLENOID_VALVE_SPEC" VARCHAR2(20 BYTE), 
	"SOLENOID_VALUE_DRIVING_FORCE" VARCHAR2(20 BYTE), 
	"SENSOR_BRAND" VARCHAR2(20 BYTE), 
	"SENSOR_NUMBER" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_BASE_EQUIPMENT_FIRE__PK" PRIMARY KEY ("EQUIPMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FIRE_FIGHT"."IMPLEMENTING_STANDARD" IS '执行标准';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FIRE_FIGHT"."HYDRA_EXPERIMENTAL_PRESSURE" IS '水压实验压力';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FIRE_FIGHT"."MAX_WORK_PRESSURE" IS '最大工作压力';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FIRE_FIGHT"."CONTROL_VALVE" IS '控制阀';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FIRE_FIGHT"."CABINET_COLOR" IS '柜体颜色';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FIRE_FIGHT"."SOLENOID_VALVE_SPEC" IS '电磁阀规格';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FIRE_FIGHT"."SOLENOID_VALUE_DRIVING_FORCE" IS '电磁阀驱动力';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FIRE_FIGHT"."SENSOR_BRAND" IS '消防感应器品牌';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FIRE_FIGHT"."SENSOR_NUMBER" IS '消防感应器数量';

  CREATE TABLE "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR" 
   (	"EQUIMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IP" VARCHAR2(20 BYTE), 
	"SETTING_TIME" VARCHAR2(20 BYTE), 
	"PORT" VARCHAR2(20 BYTE), 
	"INTAKE_MODE" VARCHAR2(20 BYTE), 
	"HUMIDIFICATION" VARCHAR2(20 BYTE), 
	"INDOOR_TEMPERATURE_HIGH_LIMIT" VARCHAR2(20 BYTE), 
	"INDOOR_TEMPERATURE_LOW_LIMIT" VARCHAR2(20 BYTE), 
	"VALVE_OPEN_DEGREE" VARCHAR2(20 BYTE), 
	"LOW_HUMIDITY_ALARM_VALUE" VARCHAR2(20 BYTE), 
	"HIGH_HUMIDITY_ALARM_VALUE" VARCHAR2(20 BYTE), 
	"FILTER_SCREEN_NUMBER" VARCHAR2(20 BYTE), 
	"FILTER_SCREEN_SPEC" VARCHAR2(20 BYTE), 
	"FILTER_SCREEN_RENEWAL_PERIOD" VARCHAR2(20 BYTE), 
	"EXHAUST_MODE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_BASE_EQUIPMENT_FRESH_PK" PRIMARY KEY ("EQUIMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."SETTING_TIME" IS '配置时间';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."INTAKE_MODE" IS '进风方式';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."HUMIDIFICATION" IS '加湿功能';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."INDOOR_TEMPERATURE_HIGH_LIMIT" IS '室内温度高限';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."INDOOR_TEMPERATURE_LOW_LIMIT" IS '室内温度低限';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."VALVE_OPEN_DEGREE" IS '阀门开启度';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."LOW_HUMIDITY_ALARM_VALUE" IS '低湿告警值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."HIGH_HUMIDITY_ALARM_VALUE" IS '高湿告警值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."FILTER_SCREEN_NUMBER" IS '过滤网个数';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."FILTER_SCREEN_SPEC" IS '过滤网规格';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."FILTER_SCREEN_RENEWAL_PERIOD" IS '滤网更换周期';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"."EXHAUST_MODE" IS '出风方式';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_BASE_EQUIPMENT_FRESH_AIR"  IS '新风设备';

  CREATE TABLE "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IP" VARCHAR2(20 BYTE), 
	"PORT" VARCHAR2(20 BYTE), 
	"REFRIGERATING_MODE" VARCHAR2(20 BYTE), 
	"HUMIDIFICATION_MODE" VARCHAR2(20 BYTE), 
	"TEMPERATURE_SET_VALUE" VARCHAR2(20 BYTE), 
	"HUMIDITY_SET_VALUE" VARCHAR2(20 BYTE), 
	"ADMIN_PASSWORD" VARCHAR2(20 BYTE), 
	"MACHINE_NUMBER" VARCHAR2(20 BYTE), 
	"LOW_TEMP_WARNING_VALUE" VARCHAR2(20 BYTE), 
	"HIGH_TEMP_WARNING_VALUE" VARCHAR2(20 BYTE), 
	"LOW_HUMIDITY_WARNING_VALUE" VARCHAR2(20 BYTE), 
	"HIGH_HUMIDITY_WARNING_VALUE" VARCHAR2(20 BYTE), 
	"FILTER_SCREEN_NUMBER" VARCHAR2(20 BYTE), 
	"FILTER_SCREEN_SPEC" VARCHAR2(20 BYTE), 
	"FILTER_SCREEN_RENEWAL_TIME" VARCHAR2(20 BYTE), 
	"EXHAUST_MODE" VARCHAR2(20 BYTE), 
	"ATTENTIONS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_BASE_EQUIPMENT_REFRI_PK" PRIMARY KEY ("EQUIPMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."REFRIGERATING_MODE" IS '制冷方式';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."HUMIDIFICATION_MODE" IS '加湿方式';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."TEMPERATURE_SET_VALUE" IS '温度设定值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."HUMIDITY_SET_VALUE" IS '湿度设定值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."ADMIN_PASSWORD" IS '管理员密码';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."MACHINE_NUMBER" IS '单双机模式';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."LOW_TEMP_WARNING_VALUE" IS '低温警告值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."HIGH_TEMP_WARNING_VALUE" IS '高温警告值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."LOW_HUMIDITY_WARNING_VALUE" IS '低湿警告值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."HIGH_HUMIDITY_WARNING_VALUE" IS '高湿警告值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."FILTER_SCREEN_NUMBER" IS '过滤网个数';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."FILTER_SCREEN_SPEC" IS '过滤网规格';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."FILTER_SCREEN_RENEWAL_TIME" IS '滤网更换时间';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."EXHAUST_MODE" IS '出风方式';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"."ATTENTIONS" IS '注意事项';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_BASE_EQUIPMENT_REFRIGERAT"  IS '制冷设备';

  CREATE TABLE "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IP" VARCHAR2(20 BYTE), 
	"PORT" VARCHAR2(20 BYTE), 
	"MACHINE_NUMBER" VARCHAR2(20 BYTE), 
	"POWER_STANDARD_HOURS" VARCHAR2(20 BYTE), 
	"BATTERY_RATED_CAPACITY" VARCHAR2(20 BYTE), 
	"INPUT_VOLTAGE" VARCHAR2(20 BYTE), 
	"BATTERY_STANDBY_VOLTAGE" VARCHAR2(20 BYTE), 
	"BATTERY_CHARGING_VOLTAGE" VARCHAR2(20 BYTE), 
	"BATTERY_SPEC" VARCHAR2(20 BYTE), 
	"BATTERY_NUMBER" VARCHAR2(20 BYTE), 
	"BATTERY_MAX_INITIAL_CURRENT" VARCHAR2(20 BYTE), 
	"BATTERY_RATED_VOLTAGE" VARCHAR2(20 BYTE), 
	"OUTPUT_CURRENT" VARCHAR2(20 BYTE), 
	"OUTPUT_VOLTAGE" VARCHAR2(20 BYTE), 
	"LOAD_1" VARCHAR2(20 BYTE), 
	"LOAD_2" VARCHAR2(20 BYTE), 
	"LOAD_3" VARCHAR2(20 BYTE), 
	"SUPPLYING_EQUIPMENT_LIST" VARCHAR2(20 BYTE), 
	"POWER_SUPPLY_STANDARD" VARCHAR2(20 BYTE), 
	"ATTENTIONS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_BASE_EQUIPMENT_UPS_PK" PRIMARY KEY ("EQUIPMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."MACHINE_NUMBER" IS '单双机';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."POWER_STANDARD_HOURS" IS '供电时长';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."BATTERY_RATED_CAPACITY" IS '电池额定容量';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."INPUT_VOLTAGE" IS '输入电压';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."BATTERY_STANDBY_VOLTAGE" IS '电池待机电压';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."BATTERY_CHARGING_VOLTAGE" IS '电池充电电压';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."BATTERY_SPEC" IS '电池规格';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."BATTERY_NUMBER" IS '电池数量';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."BATTERY_MAX_INITIAL_CURRENT" IS '电池最大初始电流';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."BATTERY_RATED_VOLTAGE" IS '电池额定电压';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."OUTPUT_CURRENT" IS '输出电流';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."OUTPUT_VOLTAGE" IS '输出电压';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."LOAD_1" IS '负载1值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."LOAD_2" IS '负载2值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."LOAD_3" IS '负载3值';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."SUPPLYING_EQUIPMENT_LIST" IS 'UPS所供设备明细';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."POWER_SUPPLY_STANDARD" IS '供电标准';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"."ATTENTIONS" IS '注意事项';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_BASE_EQUIPMENT_UPS"  IS 'UPS设备';

  CREATE TABLE "GDZC_CZ"."GDZC_BUSINESS_SYSTEM" 
   (	"SYSTEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SYSTEM_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_BUSINESS_SYSTEM_PK" PRIMARY KEY ("SYSTEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_BUSINESS_SYSTEM"."SYSTEM_NAME" IS '业务系统名称';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_BUSINESS_SYSTEM"  IS '承载业务系统';

  CREATE TABLE "GDZC_CZ"."GDZC_CONFIG_NETWORK" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SYSTEM_VERSION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MANAGE_IP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"HARDWARE_CONFIG" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DITAIL_CONFIG_FILES" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_NETWORK_CONFIG_INFO_PK" PRIMARY KEY ("EQUIPMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_NETWORK"."SYSTEM_VERSION" IS '系统版本';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_NETWORK"."MANAGE_IP" IS '管理ip，lookback地址或设备管理地址。格式：*.*.*.*,范围0-255';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_NETWORK"."HARDWARE_CONFIG" IS '硬件配置：板卡名称、数量，详细信息';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_NETWORK"."DITAIL_CONFIG_FILES" IS '详细配置 （附件上传，可以多个，上传日期和上传账户）';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_CONFIG_NETWORK"  IS '网络设备配置信息表';

  CREATE TABLE "GDZC_CZ"."GDZC_CONFIG_SAFETY_EQUIPMENT" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE), 
	"MANAGE_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LOGIN_USERNAME" VARCHAR2(20 BYTE), 
	"RUNNING_MODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USE" VARCHAR2(20 BYTE), 
	"TECH_PARAMS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_SAFETY_EQUIPMENT"."MANAGE_ADDRESS" IS '管理地址(*.*.*.*)';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_SAFETY_EQUIPMENT"."LOGIN_USERNAME" IS '登录名';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_SAFETY_EQUIPMENT"."RUNNING_MODE" IS '运行模式（单机、双机、负载）';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_SAFETY_EQUIPMENT"."USE" IS '用途';

  CREATE TABLE "GDZC_CZ"."GDZC_CONFIG_SERVER" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"OPERATION_SYSTEM" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"APPLICATIONS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"REAL_IP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SERVE_IP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SERVE_PORT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_CONFIG_SERVER_PK" PRIMARY KEY ("EQUIPMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_SERVER"."OPERATION_SYSTEM" IS '操作系统(码表)';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_SERVER"."APPLICATIONS" IS '应用软件';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_SERVER"."REAL_IP" IS '真实IP';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_SERVER"."SERVE_IP" IS '服务ip';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_SERVER"."SERVE_PORT" IS '服务端口';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_CONFIG_SERVER"  IS '服务器配置信息表';

  CREATE TABLE "GDZC_CZ"."GDZC_CONFIG_STORAGE" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MANAGE_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TECH_PARAMS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_CONFIG_STORAGE_PK" PRIMARY KEY ("EQUIPMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_STORAGE"."MANAGE_ADDRESS" IS '管理地址';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_STORAGE"."TECH_PARAMS" IS '技术参数';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_CONFIG_STORAGE"  IS '存储配置信息表';

  CREATE TABLE "GDZC_CZ"."GDZC_CONFIG_VIDEO_CONFERENCE" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MANAGE_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LOGIN_USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_CONFIG_VIDEO_CONFERE_PK" PRIMARY KEY ("EQUIPMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_VIDEO_CONFERENCE"."LOGIN_USERNAME" IS '登录名';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_CONFIG_VIDEO_CONFERENCE"."USE" IS '用途';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_CONFIG_VIDEO_CONFERENCE"  IS '视频会议配置信息表';

  CREATE TABLE "GDZC_CZ"."GDZC_DEPT" 
   (	"DEPT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_DEPT_PK" PRIMARY KEY ("DEPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_DEPT"."DEPT_NAME" IS '全局业务处室,市级预算单位,县级预算单位,县级财政';

  CREATE TABLE "GDZC_CZ"."GDZC_EQUIPMENT_BASE" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_POSITION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_BRAND" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_MODEL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_SERIAL_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DEPTID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BUSINESS_SYSTEM" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PURCHASE_DATE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROJECT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SUPPLIER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TIME_OF_WARRANTY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROJECT_MANAGER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONTACT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TECH_PARAMS" VARCHAR2(400 BYTE), 
	"MAN_IN_CHARGE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_BASE_INFO_PK" PRIMARY KEY ("EQUIPMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."EQUIPMENT_NAME" IS '设备名称';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."EQUIPMENT_POSITION" IS '设备位置';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."EQUIPMENT_BRAND" IS '设备品牌';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."EQUIPMENT_MODEL" IS '设备型号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."EQUIPMENT_SERIAL_NUMBER" IS '设备序列号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."DEPTID" IS '使用处室(可多选)';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."BUSINESS_SYSTEM" IS '承载业务系统';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."PURCHASE_DATE" IS '购买时间(年-月)';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."PROJECT" IS '项目名称';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."SUPPLIER" IS '供货公司';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."TIME_OF_WARRANTY" IS '质保期(1/2/3/4/5/6/终身)';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."PROJECT_MANAGER" IS '项目经理';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."CONTACT" IS '联系方式';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."TECH_PARAMS" IS '技术参数';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_BASE"."MAN_IN_CHARGE" IS '固定资产负责人';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_EQUIPMENT_BASE"  IS '设备维修表';

  CREATE TABLE "GDZC_CZ"."GDZC_EQUIPMENT_MAINTENANCE" 
   (	"MAINTENANCE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MAINTENANCE_TITLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_MAINTENANCE_RECORD_PK" PRIMARY KEY ("MAINTENANCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

  CREATE TABLE "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR" 
   (	"TABLE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_CODE" VARCHAR2(20 BYTE), 
	"REPORT_TIME" VARCHAR2(20 BYTE), 
	"REPAIR_TIME" VARCHAR2(20 BYTE), 
	"REPAIR_DEPT" VARCHAR2(20 BYTE), 
	"REPAIR_EXPENSE" VARCHAR2(20 BYTE), 
	"REPAIR_MAN" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"FAULTS" VARCHAR2(20 BYTE), 
	"FAULT_CAUSE" VARCHAR2(20 BYTE), 
	"REPAIR_WHAT" VARCHAR2(20 BYTE), 
	"CENTER_TECHNICIAN" VARCHAR2(20 BYTE), 
	"CENTER_OFFICAL" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_EQUIPMENT_REPAIR_TAB_PK" PRIMARY KEY ("TABLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."EQUIPMENT_CODE" IS '设备';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."REPORT_TIME" IS '发现时间';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."REPAIR_TIME" IS '维修时间';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."REPAIR_DEPT" IS '维修单位';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."REPAIR_EXPENSE" IS '维修费用';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."REPAIR_MAN" IS '维修人';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."TEL" IS '联系电话';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."FAULTS" IS '故障现象';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."FAULT_CAUSE" IS '故障原因';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."REPAIR_WHAT" IS '维修内容';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."CENTER_TECHNICIAN" IS '中心技术人员';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_EQUIPMENT_REPAIR"."CENTER_OFFICAL" IS '中心负责人';

  CREATE TABLE "GDZC_CZ"."GDZC_FILE" 
   (	"FILE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(20 BYTE), 
	"CONTENT" BLOB NOT NULL ENABLE, 
	"UPLOAD_DATE" VARCHAR2(20 BYTE), 
	"UPLOAD_WHO" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_FILE_PK" PRIMARY KEY ("FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "GDZC" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_FILE"."FILE_ID" IS '文件';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_FILE"."UPLOAD_DATE" IS '上传日期';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_FILE"."UPLOAD_WHO" IS '上传人（当前登录账户）';

  CREATE TABLE "GDZC_CZ"."GDZC_MAPPING_SPACE_MOUNTPOINT" 
   (	"STORAGE_SPACEE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MOUNT_POINT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_MAPPING_SPACE_MOUNT__PK" PRIMARY KEY ("STORAGE_SPACEE_ID", "MOUNT_POINT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON TABLE "GDZC_CZ"."GDZC_MAPPING_SPACE_MOUNTPOINT"  IS '存储空间(卷)与服务器挂载点的映射关系';

  CREATE TABLE "GDZC_CZ"."GDZC_MAPPING_SPACE_WWN" 
   (	"STORAGE_SPACE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SERVER_WWN_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_MAPPING_SPACE_WWN_PK" PRIMARY KEY ("STORAGE_SPACE_ID", "SERVER_WWN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

  CREATE TABLE "GDZC_CZ"."GDZC_NETWORK_PORT" 
   (	"PORT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_CODE" VARCHAR2(20 BYTE), 
	"PORT_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PORT_STATUS" NUMBER NOT NULL ENABLE, 
	"PORT_IP" VARCHAR2(20 BYTE), 
	"PORT_VLAN" VARCHAR2(20 BYTE), 
	"IDENTIFIER" VARCHAR2(20 BYTE), 
	"CONNECTED_EQUIPMENT" VARCHAR2(20 BYTE), 
	"USE" VARCHAR2(20 BYTE), 
	"NOTE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_NETWORK_PORT_PK" PRIMARY KEY ("PORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_NETWORK_PORT"."EQUIPMENT_CODE" IS '设备编号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_NETWORK_PORT"."PORT_NAME" IS '端口名称';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_NETWORK_PORT"."PORT_STATUS" IS '(0/1,0表示down,1表示up)';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_NETWORK_PORT"."PORT_IP" IS '(*.*.*.*)';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_NETWORK_PORT"."PORT_VLAN" IS '格式vlan+vlan名称';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_NETWORK_PORT"."IDENTIFIER" IS '线标';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_NETWORK_PORT"."CONNECTED_EQUIPMENT" IS '连接设备';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_NETWORK_PORT"."USE" IS '用途';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_NETWORK_PORT"  IS '网络设备端口信息表';

  CREATE TABLE "GDZC_CZ"."GDZC_OPERATION_SYSTEM" 
   (	"SYSTEM_NAME" VARCHAR2(20 BYTE), 
	"SYSTEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_OPERATION_SYSTEM_PK" PRIMARY KEY ("SYSTEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

  CREATE TABLE "GDZC_CZ"."GDZC_POSITON" 
   (	"POSITION_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"POSITION_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"POSITION_CLASSIFY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

  CREATE TABLE "GDZC_CZ"."GDZC_PROJECT" 
   (	"PROJECT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROJECT_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_项目名称_PK" PRIMARY KEY ("PROJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

  CREATE TABLE "GDZC_CZ"."GDZC_SAFE_ACCESS_CONTROL" 
   (	"CONTROL_ID" VARCHAR2(20 BYTE), 
	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SOURCE_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESC_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STATUS" NUMBER NOT NULL ENABLE, 
	"PORT" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_ACCESS_CONTROL"."STATUS" IS '0/1,0表示禁止，1表示允许';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_ACCESS_CONTROL"."PORT" IS '格式为：tcp/udp+端口号';

  CREATE TABLE "GDZC_CZ"."GDZC_SAFE_INTERFACE" 
   (	"INTERFACE_ID" VARCHAR2(20 BYTE), 
	"INTERFACE_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"INTERFACE_DESCRIPTION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"INTERFACE_IP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"INTERFACE_VOLOCITY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PORT_MODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONNECTED_EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PORT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOTE" VARCHAR2(20 BYTE), 
	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_INTERFACE"."INTERFACE_NAME" IS '接口名称';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_INTERFACE"."INTERFACE_DESCRIPTION" IS '接口描述(连接哪个网)';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_INTERFACE"."INTERFACE_IP" IS '接口ip';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_INTERFACE"."INTERFACE_VOLOCITY" IS '接口速率(10M/100M/1000M/10G)';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_INTERFACE"."PORT_MODE" IS '端口模式(全双工/半双工/自动)';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_INTERFACE"."CONNECTED_EQUIPMENT_CODE" IS '连接设备编号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_INTERFACE"."PORT" IS '端口号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_INTERFACE"."EQUIPMENT_CODE" IS '设备编号';

  CREATE TABLE "GDZC_CZ"."GDZC_SAFE_NAT" 
   (	"TRANSLATION_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_CODE" VARCHAR2(20 BYTE), 
	"SOURCE_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESC_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PORT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TRANSLATED_SOURCE_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TRANSLATED_DESC_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TRANSLATED_PORT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOTE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_ADDRESS_TRANSLATION_PK" PRIMARY KEY ("TRANSLATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_NAT"."SOURCE_ADDRESS" IS '源地址，可以填写多个，格式*.*.*.*,范围0-255';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_NAT"."DESC_ADDRESS" IS '目的地址，可以填写多个，格式*.*.*.*,范围0-255';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_NAT"."PORT" IS '端口号，格式：TCP/UDP+数字';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_NAT"."TRANSLATED_SOURCE_ADDRESS" IS '转换后源地址，可以填写多个，格式*.*.*.*,范围0-255';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_NAT"."TRANSLATED_DESC_ADDRESS" IS '转换后目的地址，可以填写多个，格式*.*.*.*,范围0-255';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_NAT"."TRANSLATED_PORT" IS '转换后端口号，格式同port';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_SAFE_NAT"  IS '网络地址转换（net address translation）,又称地址代理';

  CREATE TABLE "GDZC_CZ"."GDZC_SAFE_NETWORK" 
   (	"INFO_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONNECTED_EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PORT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_SAFE_NETWORK_PK" PRIMARY KEY ("INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_NETWORK"."CONNECTED_EQUIPMENT_CODE" IS '连接设备编号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SAFE_NETWORK"."DESCRIPTION" IS '描述';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_SAFE_NETWORK"  IS '安全设备网络管理信息';

  CREATE TABLE "GDZC_CZ"."GDZC_SERVER_BACKUP_INFO" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BACKUP_SOFTWARE_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BACKUP_EQUIPMENT_IP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BACKUP_CONTENT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BACKUP_STRATEGY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FILE_PATH" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DATABASE_SID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BACKUP_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_SERVER_BACKUP_PK" PRIMARY KEY ("BACKUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_BACKUP_INFO"."EQUIPMENT_CODE" IS '设备编号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_BACKUP_INFO"."BACKUP_SOFTWARE_NAME" IS '备份软件名称';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_BACKUP_INFO"."BACKUP_EQUIPMENT_IP" IS '备份设备IP';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_BACKUP_INFO"."BACKUP_CONTENT" IS '备份内容';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_BACKUP_INFO"."BACKUP_STRATEGY" IS '备份策略';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_BACKUP_INFO"."FILE_PATH" IS '备份路径';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_BACKUP_INFO"."DATABASE_SID" IS '数据库SID';

  CREATE TABLE "GDZC_CZ"."GDZC_SERVER_NETWORK_INFO" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PCI_INFO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IP_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONNECTED_EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PORT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"VLAN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"NETWORK_INFO_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_SERVER_NETWORK_INFO_PK" PRIMARY KEY ("NETWORK_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_NETWORK_INFO"."PCI_INFO" IS 'pci板卡信息';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_NETWORK_INFO"."IP_ADDRESS" IS 'IP地址';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_NETWORK_INFO"."CONNECTED_EQUIPMENT_CODE" IS '连接设备编号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_NETWORK_INFO"."PORT" IS '端口号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_NETWORK_INFO"."VLAN" IS '端口所在vlan';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_NETWORK_INFO"."DESCRIPTION" IS '描述';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_SERVER_NETWORK_INFO"  IS '服务器网络交互信息';

  CREATE TABLE "GDZC_CZ"."GDZC_SERVER_STORAGE_INFO" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PCI_INFO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ZONE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"WWN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOTE" VARCHAR2(20 BYTE), 
	"STORAGE_INFO_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_SERVER_STORAGE_INFO_PK" PRIMARY KEY ("STORAGE_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_STORAGE_INFO"."PCI_INFO" IS 'pci板卡信息';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_STORAGE_INFO"."ZONE" IS '端口所在vlan';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_STORAGE_INFO"."WWN" IS 'world wide name';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_SERVER_STORAGE_INFO"  IS '服务器存储交互信息';

  CREATE TABLE "GDZC_CZ"."GDZC_SERVER_STORAGE_MOUNT_INFO" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MOUNTED_STORAGE_EQUIPMENT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STORAGE_VOLUME_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MOUNT_POINT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MOUNT_INFO_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_SERVER_STORAGE_MOUNT_PK" PRIMARY KEY ("MOUNT_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_STORAGE_MOUNT_INFO"."MOUNTED_STORAGE_EQUIPMENT" IS '挂载的存储设备编号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_STORAGE_MOUNT_INFO"."STORAGE_VOLUME_NAME" IS '卷名称';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_SERVER_STORAGE_MOUNT_INFO"."MOUNT_POINT" IS '服务器挂载点';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_SERVER_STORAGE_MOUNT_INFO"  IS '服务器存储挂载信息';

  CREATE TABLE "GDZC_CZ"."GDZC_STORAGE_FIBER_INFO" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"WWN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONNECTED_EQUIPMENT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PORT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"VLAN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"FIBER_INFO_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PCI_INFO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_STORAGE_FIBER_INFO_PK" PRIMARY KEY ("FIBER_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_STORAGE_FIBER_INFO"."WWN" IS 'world wide name';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_STORAGE_FIBER_INFO"."CONNECTED_EQUIPMENT" IS '连接设备编号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_STORAGE_FIBER_INFO"."PORT" IS '端口';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_STORAGE_FIBER_INFO"."VLAN" IS '端口所在vlan';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_STORAGE_FIBER_INFO"."FIBER_INFO_ID" IS '交互信息记录id';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_STORAGE_FIBER_INFO"."PCI_INFO" IS 'pci板卡信息';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_STORAGE_FIBER_INFO"  IS '存储光纤交互信息';

  CREATE TABLE "GDZC_CZ"."GDZC_STORAGE_NETWORK_MANAGE" 
   (	"NET_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PCI_INFO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IP_ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONNECTED_EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PORT" VARCHAR2(20 BYTE), 
	"VLAN" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_STORAGE_NETWORK_MANA_PK" PRIMARY KEY ("NET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_STORAGE_NETWORK_MANAGE"."CONNECTED_EQUIPMENT_CODE" IS '连接设备编号';

  CREATE TABLE "GDZC_CZ"."GDZC_STORAGE_SPACE" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"VOLUME_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"VOLUME_SIZE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOTE" VARCHAR2(20 BYTE), 
	"MAPPING_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_STORAGE_SPACE_MAPPIN_PK" PRIMARY KEY ("MAPPING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_STORAGE_SPACE"."EQUIPMENT_CODE" IS '设备编号';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_STORAGE_SPACE"."VOLUME_NAME" IS '卷名称';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_STORAGE_SPACE"."VOLUME_SIZE" IS '卷大小';

  CREATE TABLE "GDZC_CZ"."GDZC_SUPPLIER" 
   (	"SUPPLIER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SUPPLIER_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GDZC_SUPPLIER_PK" PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

  CREATE TABLE "GDZC_CZ"."GDZC_VIDEO_INTERFACE" 
   (	"INTERFACE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EQUIPMENT_INTERFACE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"OPPOSITE_EQUIPMENT_CODE" VARCHAR2(20 BYTE), 
	"OPPOSITE_INTERFACE" VARCHAR2(20 BYTE), 
	"NOTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_VIDEO_INTERFACE"."EQUIPMENT_INTERFACE" IS '设备接口';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_VIDEO_INTERFACE"."USE" IS '用途';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_VIDEO_INTERFACE"."OPPOSITE_EQUIPMENT_CODE" IS '对端设备';
   COMMENT ON COLUMN "GDZC_CZ"."GDZC_VIDEO_INTERFACE"."OPPOSITE_INTERFACE" IS '对端接口';

  CREATE TABLE "GDZC_CZ"."GDZC_VIDEO_NETWORK" 
   (	"EQUIPMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PORT" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"CONNECTED_NETWORK_EQUIPMENT" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GDZC_VIDEO_NETWORK_PK" PRIMARY KEY ("EQUIPMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "GDZC"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GDZC" ;

   COMMENT ON COLUMN "GDZC_CZ"."GDZC_VIDEO_NETWORK"."CONNECTED_NETWORK_EQUIPMENT" IS '连接网络设备编号()';
   COMMENT ON TABLE "GDZC_CZ"."GDZC_VIDEO_NETWORK"  IS '视频会议网络管理信息';
